repos = [
    "github.com/BurntSushi/toml",
    "github.com/BurntSushi/toml/cmd/tomlv",
    "github.com/b4b4r07/brionac",
    "github.com/b4b4r07/gch",
    "github.com/b4b4r07/go-pipe",
    "github.com/b4b4r07/gomi/...",
    "github.com/b4b4r07/gorionac",
    "github.com/b4b4r07/xtime",
    "github.com/cheggaaa/pb",
    "github.com/codegangsta/cli",
    "github.com/daviddengcn/go-colortext",
    "github.com/jessevdk/go-flags",
    "github.com/k0kubun/pp",
    "github.com/kyokomi/emoji",
    "github.com/mattn/go-scan",
    "github.com/mattn/gof",
    "github.com/mattn/gom",
    "github.com/mgutz/ansi",
    "github.com/mitchellh/gox",
    "github.com/monochromegane/hoi",
    "github.com/motemen/ghq",
    "github.com/motemen/go-colorine",
    "github.com/nsf/gocode",
    "github.com/nsf/godit",
    "github.com/peco/peco",
    #"github.com/tcnksm/ghr",
]
