[General]
  snippetfile = "/Users/b4b4r07/.config/pet/snippet.toml"
  editor = "vim"
  column = 40
  selectcmd = "fzf"
  backend = "gist"
  sortby = ""

[Gist]
  file_name = "pet-snippet.toml"
  access_token = ""
  gist_id = ""
  public = false
  auto_sync = false

[GitLab]
  file_name = "pet-snippet.toml"
  access_token = ""
  url = ""
  id = ""
  visibility = "private"
  auto_sync = false
